// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `gender` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "gender"))]
    pub struct Gender;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Gender;

    /// Representation of the `sys_user` table.
    ///
    /// (Automatically generated by Diesel.)
    sys_user (id) {
        /// The `id` column of the `sys_user` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `username` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        username -> Varchar,
        /// The `password` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        password -> Varchar,
        /// The `email` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 150]
        email -> Nullable<Varchar>,
        /// The `phone` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 11]
        phone -> Nullable<Varchar>,
        /// The `nickname` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        nickname -> Nullable<Varchar>,
        /// The `gender` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Gender>`.
        ///
        /// (Automatically generated by Diesel.)
        gender -> Nullable<Gender>,
        /// The `avatar` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar -> Nullable<Text>,
        /// The `is_admin` column of the `sys_user` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_admin -> Bool,
        /// The `create_at` column of the `sys_user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        create_at -> Timestamptz,
        /// The `update_at` column of the `sys_user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        update_at -> Timestamptz,
        /// The `deleted_at` column of the `sys_user` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}
